export const players = [
  {
    "FIRST NAME": "Lionel",
    "LAST NAME": "Messi",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 94,
    PACE: 88,
    SHOOTING: 91,
    PASSING: 88,
    DRIBBLING: 96,
    DEFENDING: 32,
    PHYSICAL: 60,
    "": 455,
    STRENGTH: 59,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 170,
    AGE: 31,
    POS: "SS",
    card_url: "2 - Messi.png"
  },
  {
    "FIRST NAME": "C. Ronaldo",
    "LAST NAME": "dos Santos Aveiro",
    POSTE: "str",
    "COMMON NAME": "Cristiano Ronaldo",
    RATING: 94,
    PACE: 90,
    SHOOTING: 93,
    PASSING: 81,
    DRIBBLING: 89,
    DEFENDING: 35,
    PHYSICAL: 79,
    "": 467,
    STRENGTH: 79,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Portugal",
    HEIGHT: 187,
    AGE: 33,
    POS: "ST",
    card_url: "1 - Cristiano Ronaldo.png"
  },
  {
    "FIRST NAME": "Neymar",
    "LAST NAME": "da Silva Santos Jr.",
    POSTE: "str",
    "COMMON NAME": "Neymar Jr",
    RATING: 92,
    PACE: 92,
    SHOOTING: 84,
    PASSING: 83,
    DRIBBLING: 95,
    DEFENDING: 32,
    PHYSICAL: 59,
    "": 445,
    STRENGTH: 49,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 175,
    AGE: 26,
    POS: "LW",
    card_url: "3 - Neymar.png"
  },
  {
    "FIRST NAME": "Kevin",
    "LAST NAME": "De Bruyne",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 91,
    PACE: 77,
    SHOOTING: 86,
    PASSING: 92,
    DRIBBLING: 87,
    DEFENDING: 60,
    PHYSICAL: 78,
    "": 480,
    STRENGTH: 75,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 181,
    AGE: 27,
    POS: "CAM",
    card_url: "5 - De Bruyne.png"
  },
  {
    "FIRST NAME": "David",
    "LAST NAME": "De Gea Quintana",
    POSTE: "gk",
    "COMMON NAME": "De Gea",
    RATING: 91,
    PACE: 90,
    SHOOTING: 85,
    PASSING: 87,
    DRIBBLING: 94,
    DEFENDING: 57,
    PHYSICAL: 88,
    "": 501,
    STRENGTH: 64,
    TEAM: "Manchester United",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Spain",
    HEIGHT: 193,
    AGE: 27,
    POS: "GK",
    card_url: "9 - De Gea.png"
  },
  {
    "FIRST NAME": "Luka",
    "LAST NAME": "Modrić",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 91,
    PACE: 76,
    SHOOTING: 76,
    PASSING: 90,
    DRIBBLING: 91,
    DEFENDING: 70,
    PHYSICAL: 67,
    "": 470,
    STRENGTH: 58,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Croatia",
    HEIGHT: 172,
    AGE: 32,
    POS: "CM",
    card_url: "4 - Modric.png"
  },
  {
    "FIRST NAME": "Eden",
    "LAST NAME": "Hazard",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 91,
    PACE: 91,
    SHOOTING: 82,
    PASSING: 86,
    DRIBBLING: 94,
    DEFENDING: 35,
    PHYSICAL: 67,
    "": 455,
    STRENGTH: 66,
    TEAM: "Chelsea",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 173,
    AGE: 27,
    POS: "LW",
    card_url: "6 - Hazard.png"
  },
  {
    "FIRST NAME": "Luis",
    "LAST NAME": "Suárez",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 91,
    PACE: 80,
    SHOOTING: 90,
    PASSING: 79,
    DRIBBLING: 88,
    DEFENDING: 52,
    PHYSICAL: 85,
    "": 474,
    STRENGTH: 83,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Uruguay",
    HEIGHT: 182,
    AGE: 31,
    POS: "ST",
    card_url: "8 - Suarez.png"
  },
  {
    "FIRST NAME": "Sergio",
    "LAST NAME": "Ramos García",
    POSTE: "def",
    "COMMON NAME": "Sergio Ramos",
    RATING: 91,
    PACE: 75,
    SHOOTING: 63,
    PASSING: 71,
    DRIBBLING: 71,
    DEFENDING: 90,
    PHYSICAL: 84,
    "": 454,
    STRENGTH: 83,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 184,
    AGE: 32,
    POS: "CB",
    card_url: "7 - Ramos.png"
  },
  {
    "FIRST NAME": "Toni",
    "LAST NAME": "Kroos",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 67,
    SHOOTING: 82,
    PASSING: 89,
    DRIBBLING: 82,
    DEFENDING: 74,
    PHYSICAL: 69,
    "": 463,
    STRENGTH: 73,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Germany",
    HEIGHT: 183,
    AGE: 28,
    POS: "CM",
    card_url: "10 - Kroos.png"
  },
  {
    "FIRST NAME": "Manuel",
    "LAST NAME": "Neuer",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 91,
    SHOOTING: 88,
    PASSING: 91,
    DRIBBLING: 88,
    DEFENDING: 56,
    PHYSICAL: 88,
    "": 502,
    STRENGTH: 80,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 193,
    AGE: 32,
    POS: "GK",
    card_url: "12 - Neuer.png"
  },
  {
    "FIRST NAME": "Jan",
    "LAST NAME": "Oblak",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 86,
    SHOOTING: 92,
    PASSING: 78,
    DRIBBLING: 89,
    DEFENDING: 50,
    PHYSICAL: 88,
    "": 483,
    STRENGTH: 78,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Slovenia",
    HEIGHT: 188,
    AGE: 25,
    POS: "GK",
    card_url: "15 - Oblak.png"
  },
  {
    "FIRST NAME": "Thibaut",
    "LAST NAME": "Courtois",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 87,
    SHOOTING: 91,
    PASSING: 74,
    DRIBBLING: 88,
    DEFENDING: 48,
    PHYSICAL: 87,
    "": 475,
    STRENGTH: 70,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 199,
    AGE: 26,
    POS: "GK",
    card_url: "14 - Courtois.png"
  },
  {
    "FIRST NAME": "Robert",
    "LAST NAME": "Lewandowski",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 78,
    SHOOTING: 89,
    PASSING: 75,
    DRIBBLING: 85,
    DEFENDING: 41,
    PHYSICAL: 82,
    "": 450,
    STRENGTH: 84,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Poland",
    HEIGHT: 184,
    AGE: 30,
    POS: "ST",
    card_url: "11 - Lewandowski.png"
  },
  {
    "FIRST NAME": "Diego",
    "LAST NAME": "Godín",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 90,
    PACE: 68,
    SHOOTING: 48,
    PASSING: 65,
    DRIBBLING: 62,
    DEFENDING: 89,
    PHYSICAL: 84,
    "": 416,
    STRENGTH: 90,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Uruguay",
    HEIGHT: 187,
    AGE: 32,
    POS: "CB",
    card_url: "13 - Godin.png"
  },
  {
    "FIRST NAME": "David Josué",
    "LAST NAME": "Jiménez Silva",
    POSTE: "mid",
    "COMMON NAME": "David Silva",
    RATING: 89,
    PACE: 66,
    SHOOTING: 74,
    PASSING: 87,
    DRIBBLING: 90,
    DEFENDING: 50,
    PHYSICAL: 60,
    "": 427,
    STRENGTH: 52,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Spain",
    HEIGHT: 173,
    AGE: 32,
    POS: "CAM",
    card_url: "24 - David Silva.png"
  },
  {
    "FIRST NAME": "Harry",
    "LAST NAME": "Kane",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 70,
    SHOOTING: 90,
    PASSING: 79,
    DRIBBLING: 80,
    DEFENDING: 47,
    PHYSICAL: 83,
    "": 449,
    STRENGTH: 84,
    TEAM: "Tottenham Hotspur",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "England",
    HEIGHT: 188,
    AGE: 25,
    POS: "ST",
    card_url: "17 - Kane.png"
  },
  {
    "FIRST NAME": "N'Golo",
    "LAST NAME": "Kanté",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 80,
    SHOOTING: 66,
    PASSING: 77,
    DRIBBLING: 81,
    DEFENDING: 87,
    PHYSICAL: 84,
    "": 475,
    STRENGTH: 76,
    TEAM: "Chelsea",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "France",
    HEIGHT: 168,
    AGE: 27,
    POS: "CDM",
    card_url: "16 - Kante.png"
  },
  {
    "FIRST NAME": "Sergio",
    "LAST NAME": "Agüero",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 84,
    SHOOTING: 89,
    PASSING: 76,
    DRIBBLING: 89,
    DEFENDING: 28,
    PHYSICAL: 73,
    "": 439,
    STRENGTH: 73,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 173,
    AGE: 30,
    POS: "ST",
    card_url: "20 - Aguero.png"
  },
  {
    "FIRST NAME": "Marc-André",
    "LAST NAME": "ter Stegen",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 87,
    SHOOTING: 85,
    PASSING: 88,
    DRIBBLING: 90,
    DEFENDING: 43,
    PHYSICAL: 85,
    "": 478,
    STRENGTH: 79,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Germany",
    HEIGHT: 187,
    AGE: 26,
    POS: "GK",
    card_url: "25 - Ter Stegen.png"
  },
  {
    "FIRST NAME": "Francisco Román",
    "LAST NAME": "Alarcón Suárez",
    POSTE: "mid",
    "COMMON NAME": "Isco",
    RATING: 89,
    PACE: 72,
    SHOOTING: 81,
    PASSING: 85,
    DRIBBLING: 93,
    DEFENDING: 61,
    PHYSICAL: 62,
    "": 454,
    STRENGTH: 59,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 176,
    AGE: 26,
    POS: "CAM",
    card_url: "26 - Isco.png"
  },
  {
    "FIRST NAME": "Antoine",
    "LAST NAME": "Griezmann",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 86,
    SHOOTING: 86,
    PASSING: 81,
    DRIBBLING: 88,
    DEFENDING: 50,
    PHYSICAL: 70,
    "": 461,
    STRENGTH: 62,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "France",
    HEIGHT: 176,
    AGE: 27,
    POS: "ST",
    card_url: "18 - Griezmann.png"
  },
  {
    "FIRST NAME": "Paulo",
    "LAST NAME": "Dybala",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 85,
    SHOOTING: 85,
    PASSING: 84,
    DRIBBLING: 91,
    DEFENDING: 28,
    PHYSICAL: 66,
    "": 439,
    STRENGTH: 65,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 177,
    AGE: 24,
    POS: "CAM",
    card_url: "21 - Dybala.png"
  },
  {
    "FIRST NAME": "Giorgio",
    "LAST NAME": "Chiellini",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 69,
    SHOOTING: 46,
    PASSING: 56,
    DRIBBLING: 58,
    DEFENDING: 91,
    PHYSICAL: 82,
    "": 402,
    STRENGTH: 87,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Italy",
    HEIGHT: 187,
    AGE: 34,
    POS: "CB",
    card_url: "19 - Chiellini.png"
  },
  {
    "FIRST NAME": "Edinson",
    "LAST NAME": "Cavani",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 76,
    SHOOTING: 87,
    PASSING: 72,
    DRIBBLING: 80,
    DEFENDING: 52,
    PHYSICAL: 83,
    "": 450,
    STRENGTH: 78,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Uruguay",
    HEIGHT: 185,
    AGE: 31,
    POS: "ST",
    card_url: "22 - Cavani.png"
  },
  {
    "FIRST NAME": "Mats",
    "LAST NAME": "Hummels",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 89,
    PACE: 65,
    SHOOTING: 58,
    PASSING: 76,
    DRIBBLING: 72,
    DEFENDING: 90,
    PHYSICAL: 76,
    "": 437,
    STRENGTH: 85,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 191,
    AGE: 29,
    POS: "CB",
    card_url: "23 - Hummels.png"
  },
  {
    "FIRST NAME": "Christian",
    "LAST NAME": "Eriksen",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 74,
    SHOOTING: 82,
    PASSING: 89,
    DRIBBLING: 86,
    DEFENDING: 53,
    PHYSICAL: 64,
    "": 448,
    STRENGTH: 58,
    TEAM: "Tottenham Hotspur",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Denmark",
    HEIGHT: 181,
    AGE: 26,
    POS: "CAM",
    card_url: "34 - Eriksen.png"
  },
  {
    "FIRST NAME": "Philippe",
    "LAST NAME": "Coutinho Correia",
    POSTE: "mid",
    "COMMON NAME": "Coutinho",
    RATING: 88,
    PACE: 81,
    SHOOTING: 81,
    PASSING: 86,
    DRIBBLING: 91,
    DEFENDING: 44,
    PHYSICAL: 64,
    "": 447,
    STRENGTH: 61,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 172,
    AGE: 26,
    POS: "LW",
    card_url: "30 - Coutinho.png"
  },
  {
    "FIRST NAME": "Gareth",
    "LAST NAME": "Bale",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 95,
    SHOOTING: 88,
    PASSING: 84,
    DRIBBLING: 85,
    DEFENDING: 58,
    PHYSICAL: 76,
    "": 486,
    STRENGTH: 80,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Wales",
    HEIGHT: 185,
    AGE: 29,
    POS: "RW",
    card_url: "31 - Bale.png"
  },
  {
    "FIRST NAME": "Marcelo",
    "LAST NAME": "Vieira da Silva",
    POSTE: "def",
    "COMMON NAME": "Marcelo",
    RATING: 88,
    PACE: 82,
    SHOOTING: 71,
    PASSING: 83,
    DRIBBLING: 90,
    DEFENDING: 81,
    PHYSICAL: 82,
    "": 489,
    STRENGTH: 78,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 174,
    AGE: 30,
    POS: "LB",
    card_url: "28 - Marcelo.png"
  },
  {
    "FIRST NAME": "Paul",
    "LAST NAME": "Pogba",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 75,
    SHOOTING: 79,
    PASSING: 86,
    DRIBBLING: 85,
    DEFENDING: 69,
    PHYSICAL: 87,
    "": 481,
    STRENGTH: 89,
    TEAM: "Manchester United",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "France",
    HEIGHT: 191,
    AGE: 25,
    POS: "CM",
    card_url: "33 - Pogba.png"
  },
  {
    "FIRST NAME": "Sergio",
    "LAST NAME": "Busquets Burgos",
    POSTE: "mid",
    "COMMON NAME": "Sergio Busquets",
    RATING: 88,
    PACE: 43,
    SHOOTING: 62,
    PASSING: 79,
    DRIBBLING: 78,
    DEFENDING: 85,
    PHYSICAL: 80,
    "": 427,
    STRENGTH: 77,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 189,
    AGE: 30,
    POS: "CDM",
    card_url: "32 - Busquets.png"
  },
  {
    "FIRST NAME": "Carlos Henrique",
    "LAST NAME": "Venancio Casimiro",
    POSTE: "mid",
    "COMMON NAME": "Casemiro",
    RATING: 88,
    PACE: 62,
    SHOOTING: 69,
    PASSING: 74,
    DRIBBLING: 72,
    DEFENDING: 87,
    PHYSICAL: 88,
    "": 452,
    STRENGTH: 89,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 185,
    AGE: 26,
    POS: "CDM",
    card_url: "37 - Casemiro.png"
  },
  {
    "FIRST NAME": "Hugo",
    "LAST NAME": "Lloris",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 88,
    SHOOTING: 84,
    PASSING: 68,
    DRIBBLING: 92,
    DEFENDING: 64,
    PHYSICAL: 83,
    "": 479,
    STRENGTH: 43,
    TEAM: "Tottenham Hotspur",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "France",
    HEIGHT: 188,
    AGE: 31,
    POS: "GK",
    card_url: "29 - Lloris.png"
  },
  {
    "FIRST NAME": "Mohamed",
    "LAST NAME": "Salah",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 92,
    SHOOTING: 84,
    PASSING: 79,
    DRIBBLING: 89,
    DEFENDING: 45,
    PHYSICAL: 72,
    "": 461,
    STRENGTH: 70,
    TEAM: "Liverpool",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Egypt",
    HEIGHT: 175,
    AGE: 26,
    POS: "RW",
    card_url: "27 - Salah.png"
  },
  {
    "FIRST NAME": "Samir",
    "LAST NAME": "Handanovič",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 87,
    SHOOTING: 86,
    PASSING: 69,
    DRIBBLING: 89,
    DEFENDING: 53,
    PHYSICAL: 89,
    "": 473,
    STRENGTH: 71,
    TEAM: "Inter",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Slovenia",
    HEIGHT: 193,
    AGE: 34,
    POS: "GK",
    card_url: "39 - Handanovic.png"
  },
  {
    "FIRST NAME": "Lorenzo",
    "LAST NAME": "Insigne",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 90,
    SHOOTING: 76,
    PASSING: 84,
    DRIBBLING: 91,
    DEFENDING: 36,
    PHYSICAL: 50,
    "": 427,
    STRENGTH: 44,
    TEAM: "Napoli",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Italy",
    HEIGHT: 163,
    AGE: 27,
    POS: "LW",
    card_url: "40 - Insigne.png"
  },
  {
    "FIRST NAME": "Gonzalo",
    "LAST NAME": "Higuaín",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 73,
    SHOOTING: 87,
    PASSING: 70,
    DRIBBLING: 83,
    DEFENDING: 31,
    PHYSICAL: 74,
    "": 418,
    STRENGTH: 85,
    TEAM: "Milan",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 186,
    AGE: 30,
    POS: "ST",
    card_url: "38 - Higuain.png"
  },
  {
    "FIRST NAME": "Gianluigi",
    "LAST NAME": "Buffon",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 88,
    SHOOTING: 87,
    PASSING: 74,
    DRIBBLING: 83,
    DEFENDING: 47,
    PHYSICAL: 90,
    "": 469,
    STRENGTH: 69,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Italy",
    HEIGHT: 192,
    AGE: 40,
    POS: "GK",
    card_url: "35 - Buffon.png"
  },
  {
    "FIRST NAME": "James",
    "LAST NAME": "Rodríguez",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 88,
    PACE: 72,
    SHOOTING: 86,
    PASSING: 88,
    DRIBBLING: 86,
    DEFENDING: 50,
    PHYSICAL: 67,
    "": 449,
    STRENGTH: 68,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Colombia",
    HEIGHT: 181,
    AGE: 27,
    POS: "CAM",
    card_url: "36 - Rodriguez.png"
  },
  {
    "FIRST NAME": "Thiago Emiliano",
    "LAST NAME": "da Silva",
    POSTE: "def",
    "COMMON NAME": "Thiago Silva",
    RATING: 88,
    PACE: 71,
    SHOOTING: 54,
    PASSING: 73,
    DRIBBLING: 69,
    DEFENDING: 88,
    PHYSICAL: 79,
    "": 434,
    STRENGTH: 82,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 183,
    AGE: 33,
    POS: "CB",
    card_url: "41 - Thiago Silva.png"
  },
  {
    "FIRST NAME": "Andrés",
    "LAST NAME": "Iniesta Luján",
    POSTE: "mid",
    "COMMON NAME": "Iniesta",
    RATING: 87,
    PACE: 69,
    SHOOTING: 70,
    PASSING: 87,
    DRIBBLING: 90,
    DEFENDING: 61,
    PHYSICAL: 57,
    "": 434,
    STRENGTH: 58,
    TEAM: "Vissel Kobe",
    LEAGUE: "Japan J1 League (1)",
    NATIONALITY: "Spain",
    HEIGHT: 171,
    AGE: 34,
    POS: "CM",
    card_url: "50 - Iniesta.png"
  },
  {
    "FIRST NAME": "Alexis",
    "LAST NAME": "Sánchez",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 82,
    SHOOTING: 83,
    PASSING: 79,
    DRIBBLING: 89,
    DEFENDING: 45,
    PHYSICAL: 77,
    "": 455,
    STRENGTH: 72,
    TEAM: "Manchester United",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Chile",
    HEIGHT: 169,
    AGE: 29,
    POS: "LW",
    card_url: "56 - Sanchez.png"
  },
  {
    "FIRST NAME": "Ivan",
    "LAST NAME": "Rakitić",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 62,
    SHOOTING: 84,
    PASSING: 87,
    DRIBBLING: 82,
    DEFENDING: 72,
    PHYSICAL: 69,
    "": 456,
    STRENGTH: 66,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Croatia",
    HEIGHT: 184,
    AGE: 30,
    POS: "CM",
    card_url: "44 - Rakitic.png"
  },
  {
    "FIRST NAME": "Romelu",
    "LAST NAME": "Lukaku",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 84,
    SHOOTING: 84,
    PASSING: 76,
    DRIBBLING: 75,
    DEFENDING: 35,
    PHYSICAL: 87,
    "": 441,
    STRENGTH: 94,
    TEAM: "Manchester United",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 190,
    AGE: 25,
    POS: "ST",
    card_url: "45 - Lukaku.png"
  },
  {
    "FIRST NAME": "Pierre-Emerick",
    "LAST NAME": "Aubameyang",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 94,
    SHOOTING: 84,
    PASSING: 75,
    DRIBBLING: 80,
    DEFENDING: 37,
    PHYSICAL: 70,
    "": 440,
    STRENGTH: 76,
    TEAM: "Arsenal",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Gabon",
    HEIGHT: 187,
    AGE: 29,
    POS: "ST",
    card_url: "51 - Aubameyang.png"
  },
  {
    "FIRST NAME": "Marek",
    "LAST NAME": "Hamšík",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 70,
    SHOOTING: 80,
    PASSING: 84,
    DRIBBLING: 84,
    DEFENDING: 72,
    PHYSICAL: 69,
    "": 459,
    STRENGTH: 67,
    TEAM: "Napoli",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Slovakia",
    HEIGHT: 183,
    AGE: 31,
    POS: "CM",
    card_url: "46 -Hamsik.png"
  },
  {
    "FIRST NAME": "Dries",
    "LAST NAME": "Mertens",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 89,
    SHOOTING: 83,
    PASSING: 80,
    DRIBBLING: 91,
    DEFENDING: 34,
    PHYSICAL: 55,
    "": 432,
    STRENGTH: 42,
    TEAM: "Napoli",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 169,
    AGE: 31,
    POS: "SS",
    card_url: "54 - Mertens.png"
  },
  {
    "FIRST NAME": "Jan",
    "LAST NAME": "Vertonghen",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 63,
    SHOOTING: 63,
    PASSING: 72,
    DRIBBLING: 72,
    DEFENDING: 88,
    PHYSICAL: 79,
    "": 437,
    STRENGTH: 79,
    TEAM: "Tottenham Hotspur",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 189,
    AGE: 31,
    POS: "CB",
    card_url: "48 - Vertonghen.png"
  },
  {
    "FIRST NAME": "Keylor",
    "LAST NAME": "Navas",
    POSTE: "gk",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 90,
    SHOOTING: 81,
    PASSING: 75,
    DRIBBLING: 90,
    DEFENDING: 54,
    PHYSICAL: 82,
    "": 472,
    STRENGTH: 75,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Costa Rica",
    HEIGHT: 185,
    AGE: 31,
    POS: "GK",
    card_url: "52 - Navas.png"
  },
  {
    "FIRST NAME": "Ciro",
    "LAST NAME": "Immobile",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 82,
    SHOOTING: 86,
    PASSING: 63,
    DRIBBLING: 82,
    DEFENDING: 39,
    PHYSICAL: 76,
    "": 428,
    STRENGTH: 76,
    TEAM: "Lazio",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Italy",
    HEIGHT: 185,
    AGE: 28,
    POS: "ST",
    card_url: "57 - Immobile.png"
  },
  {
    "FIRST NAME": "Jordi",
    "LAST NAME": "Alba Ramos",
    POSTE: "def",
    "COMMON NAME": "Jordi Alba",
    RATING: 87,
    PACE: 93,
    SHOOTING: 69,
    PASSING: 79,
    DRIBBLING: 83,
    DEFENDING: 79,
    PHYSICAL: 72,
    "": 475,
    STRENGTH: 61,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 170,
    AGE: 29,
    POS: "LB",
    card_url: "49 - Jordi Alba.png"
  },
  {
    "FIRST NAME": "Samuel",
    "LAST NAME": "Umtiti",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 72,
    SHOOTING: 64,
    PASSING: 71,
    DRIBBLING: 72,
    DEFENDING: 88,
    PHYSICAL: 82,
    "": 449,
    STRENGTH: 84,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "France",
    HEIGHT: 182,
    AGE: 24,
    POS: "CB",
    card_url: "47 - Umititi.png"
  },
  {
    "FIRST NAME": "Gerard",
    "LAST NAME": "Piqué Bernabeu",
    POSTE: "def",
    "COMMON NAME": "Piqué",
    RATING: 87,
    PACE: 55,
    SHOOTING: 61,
    PASSING: 69,
    DRIBBLING: 65,
    DEFENDING: 87,
    PHYSICAL: 76,
    "": 413,
    STRENGTH: 83,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 194,
    AGE: 31,
    POS: "CB",
    card_url: "43 - Pique.png"
  },
  {
    "FIRST NAME": "Kylian",
    "LAST NAME": "Mbappé",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 96,
    SHOOTING: 81,
    PASSING: 79,
    DRIBBLING: 89,
    DEFENDING: 39,
    PHYSICAL: 72,
    "": 456,
    STRENGTH: 71,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "France",
    HEIGHT: 178,
    AGE: 19,
    POS: "RW",
    card_url: "42 - Mbappe.png"
  },
  {
    "FIRST NAME": "Mauro",
    "LAST NAME": "Icardi",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 78,
    SHOOTING: 85,
    PASSING: 61,
    DRIBBLING: 79,
    DEFENDING: 36,
    PHYSICAL: 72,
    "": 411,
    STRENGTH: 76,
    TEAM: "Inter",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 181,
    AGE: 25,
    POS: "ST",
    card_url: "53 - Icardi.png"
  },
  {
    "FIRST NAME": "Kalidou",
    "LAST NAME": "Koulibaly",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 87,
    PACE: 72,
    SHOOTING: 26,
    PASSING: 46,
    DRIBBLING: 59,
    DEFENDING: 88,
    PHYSICAL: 86,
    "": 377,
    STRENGTH: 94,
    TEAM: "Napoli",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Senegal",
    HEIGHT: 187,
    AGE: 27,
    POS: "CB",
    card_url: "55 - Koulibaly.png"
  },
  {
    "FIRST NAME": "Mesut",
    "LAST NAME": "Özil",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 70,
    SHOOTING: 73,
    PASSING: 86,
    DRIBBLING: 85,
    DEFENDING: 24,
    PHYSICAL: 58,
    "": 396,
    STRENGTH: 57,
    TEAM: "Arsenal",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Germany",
    HEIGHT: 180,
    AGE: 29,
    POS: "CAM",
    card_url: "61 - Ozil.png"
  },
  {
    "FIRST NAME": "Ederson",
    "LAST NAME": "Santana de Moraes",
    POSTE: "gk",
    "COMMON NAME": "Ederson",
    RATING: 86,
    PACE: 85,
    SHOOTING: 80,
    PASSING: 90,
    DRIBBLING: 87,
    DEFENDING: 64,
    PHYSICAL: 82,
    "": 488,
    STRENGTH: 68,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 188,
    AGE: 25,
    POS: "GK",
    card_url: "66 - Ederson.png"
  },
  {
    "FIRST NAME": "Thiago",
    "LAST NAME": "Alcântara",
    POSTE: "mid",
    "COMMON NAME": "Thiago",
    RATING: 86,
    PACE: 73,
    SHOOTING: 74,
    PASSING: 84,
    DRIBBLING: 90,
    DEFENDING: 66,
    PHYSICAL: 63,
    "": 450,
    STRENGTH: 59,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Spain",
    HEIGHT: 174,
    AGE: 27,
    POS: "CM",
    card_url: "62 - Thiago.png"
  },
  {
    "FIRST NAME": "Thomas",
    "LAST NAME": "Müller",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 74,
    SHOOTING: 83,
    PASSING: 80,
    DRIBBLING: 78,
    DEFENDING: 50,
    PHYSICAL: 71,
    "": 436,
    STRENGTH: 68,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 186,
    AGE: 28,
    POS: "SS",
    card_url: "67 - Muller.png"
  },
  {
    "FIRST NAME": "Roberto Firmino",
    "LAST NAME": "Barbosa de Oliveira",
    POSTE: "str",
    "COMMON NAME": "Roberto Firmino",
    RATING: 86,
    PACE: 77,
    SHOOTING: 83,
    PASSING: 80,
    DRIBBLING: 86,
    DEFENDING: 61,
    PHYSICAL: 78,
    "": 465,
    STRENGTH: 74,
    TEAM: "Liverpool",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 181,
    AGE: 26,
    POS: "SS",
    card_url: "65 - Firmino.png"
  },
  {
    "FIRST NAME": "Daniel",
    "LAST NAME": "Parejo Muñoz",
    POSTE: "mid",
    "COMMON NAME": "Parejo",
    RATING: 86,
    PACE: 47,
    SHOOTING: 80,
    PASSING: 88,
    DRIBBLING: 79,
    DEFENDING: 71,
    PHYSICAL: 71,
    "": 436,
    STRENGTH: 72,
    TEAM: "Valencia CF",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 182,
    AGE: 29,
    POS: "CM",
    card_url: "77 - Parejo.png"
  },
  {
    "FIRST NAME": "Nemanja",
    "LAST NAME": "Matić",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 56,
    SHOOTING: 71,
    PASSING: 79,
    DRIBBLING: 76,
    DEFENDING: 83,
    PHYSICAL: 83,
    "": 448,
    STRENGTH: 85,
    TEAM: "Manchester United",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Serbia",
    HEIGHT: 194,
    AGE: 30,
    POS: "CDM",
    card_url: "76 - Matic.png"
  },
  {
    "FIRST NAME": "Jérôme",
    "LAST NAME": "Boateng",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 73,
    SHOOTING: 50,
    PASSING: 72,
    DRIBBLING: 65,
    DEFENDING: 85,
    PHYSICAL: 83,
    "": 428,
    STRENGTH: 91,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 192,
    AGE: 30,
    POS: "CB",
    card_url: "68 - Boateng.png"
  },
  {
    "FIRST NAME": "Raphaël",
    "LAST NAME": "Varane",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 84,
    SHOOTING: 45,
    PASSING: 61,
    DRIBBLING: 64,
    DEFENDING: 86,
    PHYSICAL: 80,
    "": 420,
    STRENGTH: 84,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "France",
    HEIGHT: 191,
    AGE: 25,
    POS: "CB",
    card_url: "58 - Varane.png"
  },
  {
    "FIRST NAME": "Fernando Luiz",
    "LAST NAME": "Rosa",
    POSTE: "mid",
    "COMMON NAME": "Fernandinho",
    RATING: 86,
    PACE: 67,
    SHOOTING: 74,
    PASSING: 78,
    DRIBBLING: 78,
    DEFENDING: 83,
    PHYSICAL: 79,
    "": 459,
    STRENGTH: 76,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 179,
    AGE: 33,
    POS: "CDM",
    card_url: "72 - Fernandinho.png"
  },
  {
    "FIRST NAME": "Marco",
    "LAST NAME": "Verratti",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 65,
    SHOOTING: 60,
    PASSING: 84,
    DRIBBLING: 89,
    DEFENDING: 79,
    PHYSICAL: 66,
    "": 443,
    STRENGTH: 52,
    TEAM: "Paris Saint-Germain",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Italy",
    HEIGHT: 165,
    AGE: 25,
    POS: "CM",
    card_url: "64 - Verratti.png"
  },
  {
    "FIRST NAME": "César",
    "LAST NAME": "Azpilicueta Tanco",
    POSTE: "def",
    "COMMON NAME": "Azpilicueta",
    RATING: 86,
    PACE: 76,
    SHOOTING: 55,
    PASSING: 78,
    DRIBBLING: 73,
    DEFENDING: 87,
    PHYSICAL: 77,
    "": 446,
    STRENGTH: 71,
    TEAM: "Chelsea",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Spain",
    HEIGHT: 178,
    AGE: 29,
    POS: "CB",
    card_url: "74 - Azpilicueta.png"
  },
  {
    "FIRST NAME": "Ronaldo",
    "LAST NAME": "Aparecido Rodrigues",
    POSTE: "def",
    "COMMON NAME": "Naldo",
    RATING: 86,
    PACE: 63,
    SHOOTING: 69,
    PASSING: 64,
    DRIBBLING: 61,
    DEFENDING: 87,
    PHYSICAL: 74,
    "": 418,
    STRENGTH: 83,
    TEAM: "FC Schalke 04",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 198,
    AGE: 35,
    POS: "CB",
    card_url: "73 - Naldo.png"
  },
  {
    "FIRST NAME": "Leroy",
    "LAST NAME": "Sané",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 95,
    SHOOTING: 81,
    PASSING: 78,
    DRIBBLING: 86,
    DEFENDING: 38,
    PHYSICAL: 70,
    "": 448,
    STRENGTH: 70,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Germany",
    HEIGHT: 183,
    AGE: 22,
    POS: "LW",
    card_url: "70 - Sane.png"
  },
  {
    "FIRST NAME": "Miralem",
    "LAST NAME": "Pjanić",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 66,
    SHOOTING: 70,
    PASSING: 86,
    DRIBBLING: 86,
    DEFENDING: 73,
    PHYSICAL: 69,
    "": 450,
    STRENGTH: 66,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Bosnia and Herzegovina",
    HEIGHT: 178,
    AGE: 28,
    POS: "CM",
    card_url: "71 - Pjanic.png"
  },
  {
    "FIRST NAME": "Sadio",
    "LAST NAME": "Mané",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 94,
    SHOOTING: 80,
    PASSING: 76,
    DRIBBLING: 87,
    DEFENDING: 42,
    PHYSICAL: 73,
    "": 452,
    STRENGTH: 67,
    TEAM: "Liverpool",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Senegal",
    HEIGHT: 175,
    AGE: 26,
    POS: "LW",
    card_url: "60 - Mane.png"
  },
  {
    "FIRST NAME": "Nicolás",
    "LAST NAME": "Otamendi",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 60,
    SHOOTING: 57,
    PASSING: 62,
    DRIBBLING: 59,
    DEFENDING: 86,
    PHYSICAL: 80,
    "": 404,
    STRENGTH: 80,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Argentina",
    HEIGHT: 183,
    AGE: 30,
    POS: "CB",
    card_url: "63 - Otamendi.png"
  },
  {
    "FIRST NAME": "Douglas",
    "LAST NAME": "Costa de Souza",
    POSTE: "str",
    "COMMON NAME": "Douglas Costa",
    RATING: 86,
    PACE: 95,
    SHOOTING: 75,
    PASSING: 81,
    DRIBBLING: 91,
    DEFENDING: 43,
    PHYSICAL: 65,
    "": 450,
    STRENGTH: 63,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 172,
    AGE: 27,
    POS: "LM",
    card_url: "75 - Douglas Costa.png"
  },
  {
    "FIRST NAME": "Ivan",
    "LAST NAME": "Perišić",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 86,
    SHOOTING: 80,
    PASSING: 80,
    DRIBBLING: 84,
    DEFENDING: 62,
    PHYSICAL: 78,
    "": 470,
    STRENGTH: 78,
    TEAM: "Inter",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Croatia",
    HEIGHT: 186,
    AGE: 29,
    POS: "LM",
    card_url: "59 - Perisic.png"
  },
  {
    "FIRST NAME": "Alex Sandro",
    "LAST NAME": "Lobo Silva",
    POSTE: "def",
    "COMMON NAME": "Alex Sandro",
    RATING: 86,
    PACE: 85,
    SHOOTING: 65,
    PASSING: 77,
    DRIBBLING: 81,
    DEFENDING: 82,
    PHYSICAL: 83,
    "": 473,
    STRENGTH: 79,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 180,
    AGE: 27,
    POS: "LB",
    card_url: "79 - Alex Sandro.png"
  },
  {
    "FIRST NAME": "Leonardo",
    "LAST NAME": "Bonucci",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 61,
    SHOOTING: 58,
    PASSING: 69,
    DRIBBLING: 70,
    DEFENDING: 87,
    PHYSICAL: 80,
    "": 425,
    STRENGTH: 83,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Italy",
    HEIGHT: 190,
    AGE: 31,
    POS: "CB",
    card_url: "69 - Bonucci.png"
  },
  {
    "FIRST NAME": "Medhi",
    "LAST NAME": "Benatia",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 86,
    PACE: 70,
    SHOOTING: 45,
    PASSING: 54,
    DRIBBLING: 64,
    DEFENDING: 87,
    PHYSICAL: 85,
    "": 405,
    STRENGTH: 93,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Morocco",
    HEIGHT: 189,
    AGE: 31,
    POS: "CB",
    card_url: "78 - Benatia.png"
  },
  {
    "FIRST NAME": "Jorge",
    "LAST NAME": "Resurrección",
    POSTE: "mid",
    "COMMON NAME": "Koke",
    RATING: 85,
    PACE: 69,
    SHOOTING: 75,
    PASSING: 88,
    DRIBBLING: 82,
    DEFENDING: 69,
    PHYSICAL: 78,
    "": 461,
    STRENGTH: 79,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 176,
    AGE: 26,
    POS: "LM",
    card_url: "91 - Koke.png"
  },
  {
    "FIRST NAME": "Marco",
    "LAST NAME": "Asensio Willemsen",
    POSTE: "str",
    "COMMON NAME": "Marco Asensio",
    RATING: 85,
    PACE: 81,
    SHOOTING: 84,
    PASSING: 83,
    DRIBBLING: 85,
    DEFENDING: 42,
    PHYSICAL: 60,
    "": 435,
    STRENGTH: 61,
    TEAM: "Real Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 182,
    AGE: 22,
    POS: "LW",
    card_url: "95 - Marco Asensio.png"
  },
  {
    "FIRST NAME": "Joshua",
    "LAST NAME": "Kimmich",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 73,
    SHOOTING: 68,
    PASSING: 83,
    DRIBBLING: 82,
    DEFENDING: 77,
    PHYSICAL: 72,
    "": 455,
    STRENGTH: 65,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 176,
    AGE: 23,
    POS: "RB",
    card_url: "93 - Kimmich.png"
  },
  {
    "FIRST NAME": "Marco",
    "LAST NAME": "Reus",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 85,
    SHOOTING: 86,
    PASSING: 82,
    DRIBBLING: 86,
    DEFENDING: 44,
    PHYSICAL: 64,
    "": 447,
    STRENGTH: 67,
    TEAM: "Borussia Dortmund",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Germany",
    HEIGHT: 180,
    AGE: 29,
    POS: "LM",
    card_url: "90 - Reus.png"
  },
  {
    "FIRST NAME": "Alisson",
    "LAST NAME": "Ramses Becker",
    POSTE: "gk",
    "COMMON NAME": "Alisson",
    RATING: 85,
    PACE: 82,
    SHOOTING: 81,
    PASSING: 85,
    DRIBBLING: 88,
    DEFENDING: 50,
    PHYSICAL: 83,
    "": 469,
    STRENGTH: 78,
    TEAM: "Liverpool",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 191,
    AGE: 25,
    POS: "GK",
    card_url: "86 - Alisson.png"
  },
  {
    "FIRST NAME": "Arturo",
    "LAST NAME": "Vidal",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 57,
    SHOOTING: 80,
    PASSING: 79,
    DRIBBLING: 77,
    DEFENDING: 84,
    PHYSICAL: 83,
    "": 460,
    STRENGTH: 79,
    TEAM: "FC Barcelona",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Chile",
    HEIGHT: 180,
    AGE: 31,
    POS: "CDM",
    card_url: "83 - Vidal.png"
  },
  {
    "FIRST NAME": "David",
    "LAST NAME": "Alaba",
    POSTE: "def",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 82,
    SHOOTING: 73,
    PASSING: 80,
    DRIBBLING: 80,
    DEFENDING: 81,
    PHYSICAL: 75,
    "": 471,
    STRENGTH: 71,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Austria",
    HEIGHT: 180,
    AGE: 26,
    POS: "LB",
    card_url: "85 - Alaba.png"
  },
  {
    "FIRST NAME": "Zlatan",
    "LAST NAME": "Ibrahimović",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 59,
    SHOOTING: 86,
    PASSING: 77,
    DRIBBLING: 78,
    DEFENDING: 34,
    PHYSICAL: 78,
    "": 412,
    STRENGTH: 86,
    TEAM: "Los Angeles Galaxy",
    LEAGUE: "USA Major League Soccer (1)",
    NATIONALITY: "Sweden",
    HEIGHT: 195,
    AGE: 36,
    POS: "ST",
    card_url: "98 - Ibrahimovic.png"
  },
  {
    "FIRST NAME": "Filipe Luís",
    "LAST NAME": "Kasmirski",
    POSTE: "def",
    "COMMON NAME": "Filipe Luís",
    RATING: 85,
    PACE: 75,
    SHOOTING: 62,
    PASSING: 78,
    DRIBBLING: 78,
    DEFENDING: 81,
    PHYSICAL: 79,
    "": 453,
    STRENGTH: 74,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 182,
    AGE: 33,
    POS: "LB",
    card_url: "89 - Filipe Luis.png"
  },
  {
    "FIRST NAME": "Diego",
    "LAST NAME": "da Silva Costa",
    POSTE: "str",
    "COMMON NAME": "Diego Costa",
    RATING: 85,
    PACE: 75,
    SHOOTING: 83,
    PASSING: 64,
    DRIBBLING: 76,
    DEFENDING: 49,
    PHYSICAL: 87,
    "": 434,
    STRENGTH: 92,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 188,
    AGE: 29,
    POS: "ST",
    card_url: "81 - Diego Costa.png"
  },
  {
    "FIRST NAME": "Arjen",
    "LAST NAME": "Robben",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 79,
    SHOOTING: 85,
    PASSING: 80,
    DRIBBLING: 88,
    DEFENDING: 32,
    PHYSICAL: 62,
    "": 426,
    STRENGTH: 67,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "Holland",
    HEIGHT: 180,
    AGE: 34,
    POS: "RM",
    card_url: "87 - Robben.png"
  },
  {
    "FIRST NAME": "Riyad",
    "LAST NAME": "Mahrez",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 85,
    SHOOTING: 79,
    PASSING: 81,
    DRIBBLING: 90,
    DEFENDING: 37,
    PHYSICAL: 59,
    "": 431,
    STRENGTH: 55,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Algeria",
    HEIGHT: 179,
    AGE: 27,
    POS: "RW",
    card_url: "99 - Mahrez.png"
  },
  {
    "FIRST NAME": "Fábio",
    "LAST NAME": "Henrique Tavares",
    POSTE: "mid",
    "COMMON NAME": "Fabinho",
    RATING: 85,
    PACE: 71,
    SHOOTING: 69,
    PASSING: 78,
    DRIBBLING: 77,
    DEFENDING: 84,
    PHYSICAL: 84,
    "": 463,
    STRENGTH: 79,
    TEAM: "Liverpool",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "Brazil",
    HEIGHT: 188,
    AGE: 24,
    POS: "CDM",
    card_url: "84 - Fabinho.png"
  },
  {
    "FIRST NAME": "Sergej",
    "LAST NAME": "Milinković-Savić",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 69,
    SHOOTING: 79,
    PASSING: 80,
    DRIBBLING: 83,
    DEFENDING: 77,
    PHYSICAL: 84,
    "": 472,
    STRENGTH: 88,
    TEAM: "Lazio",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Serbia",
    HEIGHT: 191,
    AGE: 23,
    POS: "CM",
    card_url: "94 - Milinkovic - Savic.png"
  },
  {
    "FIRST NAME": "Raheem",
    "LAST NAME": "Sterling",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 93,
    SHOOTING: 73,
    PASSING: 76,
    DRIBBLING: 88,
    DEFENDING: 47,
    PHYSICAL: 56,
    "": 433,
    STRENGTH: 52,
    TEAM: "Manchester City",
    LEAGUE: "England Premier League (1)",
    NATIONALITY: "England",
    HEIGHT: 170,
    AGE: 23,
    POS: "RW",
    card_url: "97 - Sterling.png"
  },
  {
    "FIRST NAME": "Radja",
    "LAST NAME": "Nainggolan",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 75,
    SHOOTING: 79,
    PASSING: 78,
    DRIBBLING: 82,
    DEFENDING: 83,
    PHYSICAL: 83,
    "": 480,
    STRENGTH: 77,
    TEAM: "Inter",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "Belgium",
    HEIGHT: 176,
    AGE: 30,
    POS: "CM",
    card_url: "80 - Nainggolan.png"
  },
  {
    "FIRST NAME": "Blaise",
    "LAST NAME": "Matuidi",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 78,
    SHOOTING: 68,
    PASSING: 77,
    DRIBBLING: 79,
    DEFENDING: 83,
    PHYSICAL: 83,
    "": 468,
    STRENGTH: 76,
    TEAM: "Juventus",
    LEAGUE: "Italy Serie A (1)",
    NATIONALITY: "France",
    HEIGHT: 180,
    AGE: 31,
    POS: "CDM",
    card_url: "96 - Matuidi.png"
  },
  {
    "FIRST NAME": "Radamel Falcao",
    "LAST NAME": "García Zarate",
    POSTE: "str",
    "COMMON NAME": "Falcao",
    RATING: 85,
    PACE: 67,
    SHOOTING: 84,
    PASSING: 69,
    DRIBBLING: 78,
    DEFENDING: 43,
    PHYSICAL: 74,
    "": 415,
    STRENGTH: 75,
    TEAM: "AS Monaco",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "Colombia",
    HEIGHT: 177,
    AGE: 32,
    POS: "ST",
    card_url: "Falcao.png"
  },
  {
    "FIRST NAME": "Franck",
    "LAST NAME": "Ribéry",
    POSTE: "str",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 78,
    SHOOTING: 76,
    PASSING: 82,
    DRIBBLING: 88,
    DEFENDING: 30,
    PHYSICAL: 57,
    "": 411,
    STRENGTH: 60,
    TEAM: "Bayern München",
    LEAGUE: "Germany 1. Bundesliga (1)",
    NATIONALITY: "France",
    HEIGHT: 170,
    AGE: 35,
    POS: "LM",
    card_url: "Ribery.png"
  },
  {
    "FIRST NAME": "Nabil",
    "LAST NAME": "Fekir",
    POSTE: "mid",
    "COMMON NAME": "",
    RATING: 85,
    PACE: 79,
    SHOOTING: 82,
    PASSING: 81,
    DRIBBLING: 89,
    DEFENDING: 33,
    PHYSICAL: 79,
    "": 443,
    STRENGTH: 81,
    TEAM: "Olympique Lyonnais",
    LEAGUE: "France Ligue 1 (1)",
    NATIONALITY: "France",
    HEIGHT: 173,
    AGE: 25,
    POS: "CAM",
    card_url: "Fekir.png"
  },
  {
    "FIRST NAME": "Saúl",
    "LAST NAME": "Ñíguez Esclápez",
    POSTE: "mid",
    "COMMON NAME": "Saúl",
    RATING: 85,
    PACE: 70,
    SHOOTING: 77,
    PASSING: 79,
    DRIBBLING: 82,
    DEFENDING: 78,
    PHYSICAL: 76,
    "": 462,
    STRENGTH: 76,
    TEAM: "Atlético de Madrid",
    LEAGUE: "Spain Primera Division (1)",
    NATIONALITY: "Spain",
    HEIGHT: 184,
    AGE: 23,
    POS: "CM",
    card_url: "Saul.png"
  }
];
